version: '3'
services:
  backend:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_NO_INTERACTION: 1
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/logs/xdebug.log:/var/log/xdebug.log
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ssh2のインストールがdockerfileでできなかったのでここで実施
    command: >
      bash -c "composer install && composer dump-autoload && apache2-foreground"

  db:
    image: mysql:8.0.28
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sftp-server:
    image: atmoz/sftp
    container_name: sftp-server
    volumes:
      - ./src/sftp/files:/home/user/files
    ports:
      - "2222:22"
    command: "user:password:::files"
